/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RiccosRouteImport } from './routes/riccos'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as VisaoGeralRouteImport } from './routes/visao-geral'
import { Route as AlimentacaoIndexRouteImport } from './routes/alimentacao/index'
import { Route as AlimentacaoComprasRouteImport } from './routes/alimentacao/compras'
import { Route as AlimentacaoCorpoRouteImport } from './routes/alimentacao/corpo'
import { Route as AlimentacaoProtocoloRouteImport } from './routes/alimentacao/protocolo'
import { Route as AlimentacaoRelatoriosRouteImport } from './routes/alimentacao/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RiccosRoute = RiccosRouteImport.update({
  id: '/riccos',
  path: '/riccos',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaoGeralRoute = VisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentacaoIndexRoute = AlimentacaoIndexRouteImport.update({
  id: '/alimentacao/',
  path: '/alimentacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentacaoComprasRoute = AlimentacaoComprasRouteImport.update({
  id: '/alimentacao/compras',
  path: '/alimentacao/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentacaoCorpoRoute = AlimentacaoCorpoRouteImport.update({
  id: '/alimentacao/corpo',
  path: '/alimentacao/corpo',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentacaoProtocoloRoute = AlimentacaoProtocoloRouteImport.update({
  id: '/alimentacao/protocolo',
  path: '/alimentacao/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const AlimentacaoRelatoriosRoute = AlimentacaoRelatoriosRouteImport.update({
  id: '/alimentacao/relatorios',
  path: '/alimentacao/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/missoes': typeof MissoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/riccos': typeof RiccosRoute
  '/transacoes': typeof TransacoesRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/alimentacao/compras': typeof AlimentacaoComprasRoute
  '/alimentacao/corpo': typeof AlimentacaoCorpoRoute
  '/alimentacao/protocolo': typeof AlimentacaoProtocoloRoute
  '/alimentacao/relatorios': typeof AlimentacaoRelatoriosRoute
  '/alimentacao/': typeof AlimentacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/missoes': typeof MissoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/riccos': typeof RiccosRoute
  '/transacoes': typeof TransacoesRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/alimentacao/compras': typeof AlimentacaoComprasRoute
  '/alimentacao/corpo': typeof AlimentacaoCorpoRoute
  '/alimentacao/protocolo': typeof AlimentacaoProtocoloRoute
  '/alimentacao/relatorios': typeof AlimentacaoRelatoriosRoute
  '/alimentacao': typeof AlimentacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/missoes': typeof MissoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/riccos': typeof RiccosRoute
  '/transacoes': typeof TransacoesRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/alimentacao/compras': typeof AlimentacaoComprasRoute
  '/alimentacao/corpo': typeof AlimentacaoCorpoRoute
  '/alimentacao/protocolo': typeof AlimentacaoProtocoloRoute
  '/alimentacao/relatorios': typeof AlimentacaoRelatoriosRoute
  '/alimentacao/': typeof AlimentacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/metas'
    | '/missoes'
    | '/relatorios'
    | '/riccos'
    | '/transacoes'
    | '/visao-geral'
    | '/alimentacao/compras'
    | '/alimentacao/corpo'
    | '/alimentacao/protocolo'
    | '/alimentacao/relatorios'
    | '/alimentacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/metas'
    | '/missoes'
    | '/relatorios'
    | '/riccos'
    | '/transacoes'
    | '/visao-geral'
    | '/alimentacao/compras'
    | '/alimentacao/corpo'
    | '/alimentacao/protocolo'
    | '/alimentacao/relatorios'
    | '/alimentacao'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/metas'
    | '/missoes'
    | '/relatorios'
    | '/riccos'
    | '/transacoes'
    | '/visao-geral'
    | '/alimentacao/compras'
    | '/alimentacao/corpo'
    | '/alimentacao/protocolo'
    | '/alimentacao/relatorios'
    | '/alimentacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  MissoesRoute: typeof MissoesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RiccosRoute: typeof RiccosRoute
  TransacoesRoute: typeof TransacoesRoute
  VisaoGeralRoute: typeof VisaoGeralRoute
  AlimentacaoComprasRoute: typeof AlimentacaoComprasRoute
  AlimentacaoCorpoRoute: typeof AlimentacaoCorpoRoute
  AlimentacaoProtocoloRoute: typeof AlimentacaoProtocoloRoute
  AlimentacaoRelatoriosRoute: typeof AlimentacaoRelatoriosRoute
  AlimentacaoIndexRoute: typeof AlimentacaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riccos': {
      id: '/riccos'
      path: '/riccos'
      fullPath: '/riccos'
      preLoaderRoute: typeof RiccosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao-geral': {
      id: '/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof VisaoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alimentacao/': {
      id: '/alimentacao/'
      path: '/alimentacao'
      fullPath: '/alimentacao/'
      preLoaderRoute: typeof AlimentacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alimentacao/compras': {
      id: '/alimentacao/compras'
      path: '/alimentacao/compras'
      fullPath: '/alimentacao/compras'
      preLoaderRoute: typeof AlimentacaoComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alimentacao/corpo': {
      id: '/alimentacao/corpo'
      path: '/alimentacao/corpo'
      fullPath: '/alimentacao/corpo'
      preLoaderRoute: typeof AlimentacaoCorpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alimentacao/protocolo': {
      id: '/alimentacao/protocolo'
      path: '/alimentacao/protocolo'
      fullPath: '/alimentacao/protocolo'
      preLoaderRoute: typeof AlimentacaoProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alimentacao/relatorios': {
      id: '/alimentacao/relatorios'
      path: '/alimentacao/relatorios'
      fullPath: '/alimentacao/relatorios'
      preLoaderRoute: typeof AlimentacaoRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  MissoesRoute: MissoesRoute,
  RelatoriosRoute: RelatoriosRoute,
  RiccosRoute: RiccosRoute,
  TransacoesRoute: TransacoesRoute,
  VisaoGeralRoute: VisaoGeralRoute,
  AlimentacaoComprasRoute: AlimentacaoComprasRoute,
  AlimentacaoCorpoRoute: AlimentacaoCorpoRoute,
  AlimentacaoProtocoloRoute: AlimentacaoProtocoloRoute,
  AlimentacaoRelatoriosRoute: AlimentacaoRelatoriosRoute,
  AlimentacaoIndexRoute: AlimentacaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
