/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as TransacoesRouteImport } from './routes/transacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metas': typeof MetasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metas': typeof MetasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metas': typeof MetasRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/metas' | '/relatorios' | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/metas' | '/relatorios' | '/transacoes'
  id: '__root__' | '/' | '/metas' | '/relatorios' | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetasRoute: typeof MetasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetasRoute: MetasRoute,
  RelatoriosRoute: RelatoriosRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
